# Use root/example as user/password credentials
version: '3.9'

services:

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: jenny
      MYSQL_USER: example
      MYSQL_PASSWORD: example
